### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Panamer** [BenoitZugmeyer/eslint-plugin-html#109]
ESLint version: 3.19.0
* ESLint path: /Users/guoyw/code/webpack20181120/node_modules/eslint/lib/api.js
* Plugin version: 5.0.0
* Plugin inclusion paths: /Users/guoyw/code/webpack20181120/node_modules/eslint-plugin-html/src/index.js, /Users/guoyw/code/webpack20181120/node_modules/eslint/lib/config/plugins.js, /Users/guoyw/code/webpack20181120/node_modules/eslint/lib/config/config-file.js, /Users/guoyw/code/webpack20181120/node_modules/eslint/lib/config.js, /Users/guoyw/code/webpack20181120/node_modules/eslint/lib/cli-engine.js, /Users/guoyw/code/webpack20181120/node_modules/eslint/lib/api.js, /Users/guoyw/code/webpack20181120/node_modules/eslint-loader/index.js, /Users/guoyw/code/webpack20181120/node_modules/loader-runner/lib/loadLoader.js, /Users/guoyw/code/webpack20181120/node_modules/loader-runner/lib/LoaderRunner.js, /Users/guoyw/code/webpack20181120/node_modules/webpack/lib/NormalModule.js, /Users/guoyw/code/webpack20181120/node_modules/webpack/lib/NormalModuleFactory.js, /Users/guoyw/code/webpack20181120/node_modules/webpack/lib/Compiler.js, /Users/guoyw/code/webpack20181120/node_modules/webpack/lib/webpack.js, /Users/guoyw/code/webpack20181120/node_modules/webpack-dev-server/bin/webpack-dev-server.js
* NodeJS version: v8.11.2
* CLI arguments: ["/usr/local/bin/node","/Users/guoyw/code/webpack20181120/node_modules/.bin/webpack-dev-server","--config","build/webpack.dev.js"]
* Content of your lock file (package-lock.json or yarn.lock) or the output of `npm list`
* How did you run ESLint (via the command line? an editor plugin?)
* The following stack trace:
    at iterateESLintModules (/Users/guoyw/code/webpack20181120/node_modules/eslint-plugin-html/src/index.js:94:7)
    at Object.<anonymous> (/Users/guoyw/code/webpack20181120/node_modules/eslint-plugin-html/src/index.js:25:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.load (/Users/guoyw/code/webpack20181120/node_modules/eslint/lib/config/plugins.js:129:26)

    at iterateESLintModules (/Users/guoyw/code/webpack20181120/node_modules/eslint-plugin-html/src/index.js:79:11)
    at Object.<anonymous> (/Users/guoyw/code/webpack20181120/node_modules/eslint-plugin-html/src/index.js:25:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.load (/Users/guoyw/code/webpack20181120/node_modules/eslint/lib/config/plugins.js:129:26)

**Comment by BenoitZugmeyer** [comment]
`eslint-plugin-html` v5 requires at least `ESLint` v4.7. You seems to have `ESLint` 3.19.0. Either use `eslint-plugin-html` v3 or update `ESLint`.

**Comment by Panamer** [comment]
thanks brother
