### ISSUE TITLE
broken with eslint `5.13.0`

### ISSUE THREAD

**Issue by evilebottnawi** [BenoitZugmeyer/eslint-plugin-html#113]
## Setup configuration

* ESLint version: 5.13.0
* eslint-plugin-html version: 5.0.0
* NodeJS version: v10.15.0
* Operating System name and version: Ubuntu 18.10
* ESLint configuration (.eslintrc): don't has sense, any

* Editor name and version: no
* Plugin name and version: no

## Aditional context

```
TypeError: Cannot read property 'define' of undefined
    at verifyCodePart (/path/to/node_modules/eslint-plugin-html/src/index.js:167:18)
    at verifyWithSharedScopes (/path/to/node_modules/eslint-plugin-html/src/index.js:215:5)
    at Linter.verify (/path/to/node_modules/eslint-plugin-html/src/index.js:201:7)
    at Linter.verifyAndFix (/path/to/node_modules/eslint/lib/linter.js:1032:29)
    at processText (/path/to/node_modules/eslint/lib/cli-engine.js:197:32)
    at processFile (/path/to/node_modules/eslint/lib/cli-engine.js:241:12)
    at fileList.map.fileInfo (/path/to/node_modules/eslint/lib/cli-engine.js:613:40)
    at Array.map (<anonymous>)
    at CLIEngine.executeOnFiles (/path/to/node_modules/eslint/lib/cli-engine.js:585:34)
    at Object.execute (/path/to/node_modules/eslint/lib/cli.js:197:111)
```

**Comment by BenoitZugmeyer** [comment]
Thank you for the report. Fixed in eslint-plugin-html 5.0.1.
