### ISSUE TITLE
eslint-plugin-html error: It seems that eslint is not loaded.

### ISSUE THREAD

**Issue by WLyKan** [BenoitZugmeyer/eslint-plugin-html#50]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [eslint-plugin-html](https://github.com/BenoitZugmeyer/eslint-plugin-html) package 2.0.1

### Stack Trace

Failed to load the eslint-plugin-html package

```
At eslint-plugin-html error: It seems that eslint is not loaded. If you think it is a bug, please file a report at https://github.com/BenoitZugmeyer/eslint-plugin-html/issues

Error: eslint-plugin-html error: It seems that eslint is not loaded. If you think it is a bug, please file a report at https://github.com/BenoitZugmeyer/eslint-plugin-html/issues
    at iterateESLintModules (/packages/eslint-plugin-html/src/index.js:65:11)
    at /packages/eslint-plugin-html/src/index.js:36:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
    at /app.asar/src/atom-environment.js:792:28
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.5 
atom-beautify 0.29.17 
editorconfig 2.2.2 
javascript-snippets 1.2.1 
pigments 0.39.0 
project-folder 1.2.1 
project-manager 3.3.3 
Sublime-Style-Column-Selection 1.7.3 
svg-preview 0.11.0 
language-vue 0.21.2 
autocomplete-paths 1.0.5 
docblockr 0.9.1 
emmet 2.4.3 
eslint-plugin-html 2.0.1 
file-type-icons 1.3.3 
git-plus 7.3.3 
highlight-selected 0.12.0 
linter 1.11.23 
linter-eslint 8.1.3 
linter-jshint 3.0.3 
merge-conflicts 1.4.4 
minimap 4.26.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.5.0 
sync-settings 0.8.1 
terminal-plus 0.14.5 
```

**Comment by WLyKan** [comment]
i uninstall the atom plugin `eslint-plugin-html`, and the error is not displayed
