### ISSUE TITLE
ESLint 4 support

### ISSUE THREAD

**Issue by BenoitZugmeyer** [BenoitZugmeyer/eslint-plugin-html#57]
ESLint changed its internal API and this plugin rely heavily on patching this API.

**Comment by coljung** [comment]
Would this be causing this problem:

```
eslint-plugin-html error: It seems that eslint is not loaded. If you think it is a bug, please file a report at https://github.com/BenoitZugmeyer/eslint-plugin-html/issues
Error: eslint-plugin-html error: It seems that eslint is not loaded. If you think it is a bug, please file a report at https://github.com/BenoitZugmeyer/eslint-plugin-html/issues
    at findESLintModules (/Users/pablorincon/Documents/SSENSE/micro-services/ws-website/services/ui-website/node_modules/eslint-plugin-vue/node_modules/eslint-plugin-html/src/index.js:49:11)
    at Object.preprocess (/Users/pablorincon/Documents/SSENSE/micro-services/ws-website/services/ui-website/node_modules/eslint-plugin-vue/node_modules/eslint-plugin-html/src/index.js:100:24)
    at processText (/Users/pablorincon/Documents/SSENSE/micro-services/ws-website/services/ui-website/node_modules/eslint/lib/cli-engine.js:255:40)
    at processFile (/Users/pablorincon/Documents/SSENSE/micro-services/ws-website/services/ui-website/node_modules/eslint/lib/cli-engine.js:320:18)
    at executeOnFile (/Users/pablorincon/Documents/SSENSE/micro-services/ws-website/services/ui-website/node_modules/eslint/lib/cli-engine.js:655:25)
    at fileList.forEach.fileInfo (/Users/pablorincon/Documents/SSENSE/micro-services/ws-website/services/ui-website/node_modules/eslint/lib/cli-engine.js:693:13)
    at Array.forEach (native)
    at CLIEngine.executeOnFiles (/Users/pablorincon/Documents/SSENSE/micro-services/ws-website/services/ui-website/node_modules/eslint/lib/cli-engine.js:692:18)
    at Object.execute (/Users/pablorincon/Documents/SSENSE/micro-services/ws-website/services/ui-website/node_modules/eslint/lib/cli.js:170:107)
    at Object.<anonymous> (/Users/pablorincon/Documents/SSENSE/micro-services/ws-website/services/ui-website/node_modules/eslint/bin/eslint.js:72:28)
```

I'm also using ESlint 4 beta build

**Comment by BenoitZugmeyer** [comment]
Yup! please try to use eslint-plugin-html 3.0.0-beta.0 by installing it with `npm install eslint-plugin-html@next`. I am waiting the final release of ESLint 4 to release eslint-plugin-html 3.

**Comment by corbinu** [comment]
@BenoitZugmeyer I understand your wanting to wait but just wanted to let you know that since eslint4 is now RC they aren't allowing any further breaking changes so you should be good to release.

**Comment by kaihendry** [comment]
My toolchain is bust atm with the eslint 4 update, but good if it's fixed.

**Comment by Aladdin-ADD** [comment]
@BenoitZugmeyer  eslint@4.0.0 released.

**Comment by BenoitZugmeyer** [comment]
Yes I'm on it :)

**Comment by BenoitZugmeyer** [comment]
Aaand published! Let me know if you have any issue.
