### ISSUE TITLE
TypeError: code.originalLocation is not a function

### ISSUE THREAD

**Issue by luffyke** [BenoitZugmeyer/eslint-plugin-html#92]
package.json
```
"eslint": "^3.19.0",
"eslint-plugin-html": "^3.2.2",
```

vscode pop below error:
```
[Error - 15:19:54] ESLint stack trace:
[Error - 15:19:54] TypeError: code.originalLocation is not a function
    at remapMessages (/$myworkspace/node_modules/eslint-plugin-html/src/index.js:196:27)
    at EventEmitter.eslint.verify (/$myworkspace/node_modules/eslint-plugin-html/src/index.js:164:18)
    at processText (/$myworkspace/node_modules/eslint/lib/cli-engine.js:264:31)
    at CLIEngine.executeOnText (/$myworkspace/node_modules/eslint/lib/cli-engine.js:754:26)
    at validate (/Users/kext/.vscode/extensions/dbaeumer.vscode-eslint-1.4.8/server/out/eslintServer.js:586:26)
    at resolveSettings.then (/Users/kext/.vscode/extensions/dbaeumer.vscode-eslint-1.4.8/server/out/eslintServer.js:517:13)
    at <anonymous>
```

**Comment by BenoitZugmeyer** [comment]
That's strange. Do you still reproduce it? Can you send me the HTML file you are trying to lint?
