### ISSUE TITLE
Error: eslint-plugin-html error: It seems that eslint is not loaded.

### ISSUE THREAD

**Issue by jin9999** [BenoitZugmeyer/eslint-plugin-html#96]
at iterateESLintModules (C:\Users\zhangjinhong\AppData\Roaming\npm\node_modules\eslint-plugin-html\src\index.js:65:11)
    at Object.<anonymous> (C:\Users\zhangjinhong\AppData\Roaming\npm\node_modules\eslint-plugin-html\src\index.js:36:1)
    at Object.<anonymous> (C:\Users\zhangjinhong\AppData\Roaming\npm\node_modules\eslint-plugin-html\src\index.js:245:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

**Comment by BenoitZugmeyer** [comment]
Update the plugin to the latest version (v4.0.4) and if you still have the error, please add all requested informations to this issue.
